# Use root/example as user/password credentials
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017 # to be only exposed in testing env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMINUSERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMINPASSWORD:-example}

  backend:
    image: docker.io/dmdhrumilmistry/defect-detect-backend
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - mongo
    env_file:
      - docker.env
    